set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(MINGW_TRIPLET x86_64-w64-mingw32 CACHE STRING "MinGW target triplet")
set(MINGW_ROOT "/usr/${MINGW_TRIPLET}" CACHE PATH "MinGW target sysroot")

set(CMAKE_C_COMPILER "${MINGW_TRIPLET}-gcc" CACHE FILEPATH "MinGW C compiler")
set(CMAKE_CXX_COMPILER "${MINGW_TRIPLET}-g++" CACHE FILEPATH "MinGW C++ compiler")
set(CMAKE_RC_COMPILER "${MINGW_TRIPLET}-windres" CACHE FILEPATH "MinGW resource compiler")

set(CMAKE_FIND_ROOT_PATH "${MINGW_ROOT}")

if(DEFINED DNSBENCH_WINDOWS_PREFIX)
    list(PREPEND CMAKE_PREFIX_PATH "${DNSBENCH_WINDOWS_PREFIX}")
    list(PREPEND CMAKE_FIND_ROOT_PATH "${DNSBENCH_WINDOWS_PREFIX}")
endif()

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
